# Generated by Django 3.1.2 on 2020-10-07 14:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JednostkaOrganizacyjna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('opis', models.CharField(max_length=500, verbose_name='Opis')),
            ],
        ),
        migrations.CreateModel(
            name='SeriaPomiarowa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nazwa_sesji', models.CharField(max_length=100, verbose_name='nazwa sesji')),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=120, unique=True, verbose_name='Login')),
                ('haslo', models.CharField(max_length=120, unique=True, verbose_name='Haslo')),
                ('isSuperuser', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SesjaUzytkownika',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7dd63919-9395-4ed6-8348-6a7105313c54'), editable=False, primary_key=True, serialize=False)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Pomiar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('czyWazny', models.BooleanField(verbose_name='Czy ważny?')),
                ('wartosc', models.CharField(max_length=300, verbose_name='wartość')),
                ('data_pomiaru', models.DateField(verbose_name='data pomiaru')),
                ('sesja_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sesjauzytkownika')),
            ],
        ),
        migrations.CreateModel(
            name='LogPomiarowy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opis', models.CharField(max_length=500)),
                ('data', models.DateField()),
                ('pomiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pomiar')),
            ],
        ),
        migrations.CreateModel(
            name='LogAdministracyjny',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opis', models.CharField(max_length=500, verbose_name='Opis')),
                ('data', models.DateField(verbose_name='Data')),
                ('czynnosc', models.CharField(max_length=200, verbose_name='Czynność')),
                ('jednostka_organizacyjna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jednostkaorganizacyjna', verbose_name='Jednostka organizacyjna')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uzytkownik', verbose_name='Użytkownik')),
            ],
        ),
    ]
