# Generated by Django 3.1.2 on 2020-10-09 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201009_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesjauzytkownika',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14a13280-6278-454e-b28e-be6c0764b2cf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
