# Generated by Django 3.1.2 on 2020-10-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201012_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomiar',
            options={'ordering': ['data_pomiaru'], 'verbose_name': 'Pomiar', 'verbose_name_plural': 'Pomiary'},
        ),
        migrations.RemoveField(
            model_name='pomiar',
            name='stworzona',
        ),
        migrations.AlterField(
            model_name='pomiar',
            name='data_pomiaru',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data pomiaru'),
        ),
    ]
