# Generated by Django 3.1.2 on 2020-10-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_pomiar_sesja_uzytkownika'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logpomiarowy',
            name='pomiar',
        ),
    ]
