# Generated by Django 3.1.2 on 2020-10-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_logpomiarowy_pomiar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logadministracyjny',
            name='jednostka_organizacyjna',
        ),
        migrations.RemoveField(
            model_name='logadministracyjny',
            name='uzytkownik',
        ),
    ]
